import type { SubscriptionPlan } from '../types'

/** Shown when the plans API is unreachable or returns no active plans (matches seed_data). */
export const FALLBACK_PLANS: SubscriptionPlan[] = [
  {
    id: 0,
    slug: 'monthly-starter',
    name: 'Starter',
    description: 'Explore up to 5 minerals per month with Terra insights and map tools',
    billing_cycle: 'monthly',
    price: '50000',
    currency: 'TZS',
    included_minerals: [],
    included_mineral_names: [],
    included_report_downloads: 1,
    included_assistant_credits: 1500,
    max_explorable_minerals: 5,
  },
  {
    id: 0,
    slug: 'monthly-standard',
    name: 'Plus',
    description: 'Terra insights, show-on-map, full intelligence, analytics, and 3 PDF downloads per month',
    billing_cycle: 'monthly',
    price: '100000',
    currency: 'TZS',
    included_minerals: [],
    included_mineral_names: ['Gold', 'Graphite', 'Tanzanite'],
    included_report_downloads: 3,
    included_assistant_credits: 3000,
    max_explorable_minerals: 10,
    includes_saved_explorations: true,
  },
  {
    id: 0,
    slug: 'annual-standard',
    name: 'Pro',
    description: 'Full year: unlimited mineral exploration, full intelligence, analytics, and 10 PDF downloads',
    billing_cycle: 'annual',
    price: '1800000',
    currency: 'TZS',
    included_minerals: [],
    included_mineral_names: ['Gold', 'Graphite', 'Tanzanite'],
    included_report_downloads: 10,
    included_assistant_credits: 5000,
    max_explorable_minerals: null,
    includes_saved_explorations: true,
  },
]
